languageCode: "en-us"
title: "Zacarias Music"
canonifyurls: true
params:
  Logo: "/assets/images/TempPic.png"
metaDataFormat: "yaml"
blackfriday:
  plainIdAnchors: true
  extension:
    - autoHeaderId
